version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./server/src:/app/src
    environment:
      - PORT="3002"
      - MONGODB_URI='mongodb+srv://naeemkhandakar5:Employee123@clusteremployee.d0mcnuz.mongodb.net/?retryWrites=true&w=majority&appName=ClusterEmployee'
      - SECRET_KEY="Naeem123"

  emp-frontend:
    build:
      context: ./emp-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./emp-frontend/src:/app/src
